version: "3"

networks:
  default:
    name: pih-rs
services:
  # backend:
  #   container_name: pih-rs-api
  #   image: christofflinde/pih-rs
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./.env
  #     - ./.env.override
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  db:
    container_name: pih-rs-db
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5439:5432"
    restart: always
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
